# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ModelingSignals' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ModelingSignals

  target 'ModelingSignalsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ModelingSignalsUITests' do
    # Pods for testing
  end
  pod 'Charts'

end
